### ISSUE TITLE
Example of ingest mode cannot be built

### ISSUE THREAD

**Issue by 7SXzK3yG** [pleshevskiy/sonic-channel#1]
The example of Search mode can be built and run successfully, while two errors are reported in the example of Ingest mode. (sonic-channel v0.2.1)

Line 17:
```rust
ChannelMode::Ingest,
```
error[E0599]: no variant or associated item named `Ingest` found for enum `sonic_channel::channel::ChannelMode` in the current scope

Line 22:
```rust
let pushed = channel.push("collection", "bucket", "object:1", "my best recipe")?;
```
error[E0599]: no method named `push` found for struct `sonic_channel::channel::SonicChannel` in the current scope

**Comment by pleshevskiy** [comment]
Hello! You need to install sonic-channel with ingest feature. Only search mode enabled by default.

```
[package]
name = "my-crate"
version = "0.2.0"
authors = ["Me <user@rust-lang.org>"]

[dependencies]
sonic-channel = { version = "0.2", features = ["ingest"] }
```
