### ISSUE TITLE
query_with_limit  fails with error: WrongSonicResponse 

### ISSUE THREAD

**Issue by makorne** [pleshevskiy/sonic-channel#8]
### Describe the bug
60mb sonic db, same search word with high occurrence in db.

query()  - get 3 results
query_with_limit (  10/20  ) -  get 10/20 results
query_with_limit (  21 / more ) -  long search which fails with` error: Error { kind: WrongSonicResponse `}

### Expected behavior
1)  Should work with query_with_limit(21/1000) in some reasonable time and without errors.
      May be need to add  TTL?
2) query() must get more than 3 results   

### Environments
 - OS:  Fedora 34, SSD
 - Rust version: 1.55.0 (c8dfcfe04 2021-09-06)
 - Sonic version:  last from cargo
 - Sonic-Channel version : sonic-channel = { version = "0.4", features = ["ingest", "search"] }

**Comment by pleshevskiy** [comment]
Thank you!
This behavior is not observed on my data and I have not been able to reproduce it. It would be very helpful if you could send me the `sonic` server log, an example of using the library and test data to reproduce this problem.

**Comment by makorne** [comment]
Looks I found the issue, it is because of settings in sonic config file.
To reproduce just set this:

```
[channel.search]
query_limit_default = 3
query_limit_maximum = 20
```
I cant change config now to check this because sonic is still ingesting data, all day already...
